---
- connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - netbox.netbox
  tasks:
    - name: Create device role within Netbox with only required information
      include_role:
        name: netbox_device_role
      vars:
        netbox_url: http://netbox.local
        netbox_token: cfd7398f441e98094b656ea9a0263b06c5e87f2
        data:
          name: Test device role
          color: FFFFFF
        state: present

    - name: Create site within Netbox with only required information
      netbox_site:
        netbox_url: http://netbox.local
        netbox_token: cfd7398f441e98094b656ea9a0263b06c5e87f2
        data:
          name: My Own Site
        state: present
